import React from 'react';
import { PageTemplate } from '@/templates/PageTemplate';
import { SignUpWrapper, HeaderSign, FormWrapper } from './index.style';
import  Button from '@/components/Button/Button';
import * as Yup from 'yup';
import {useFormik} from 'formik';
import Head from 'next/head';
import styled, {css} from 'styled-components';
import { signupuser } from '@/redux/reducer/register';
import { useAppDispatch, useAppSelector } from  '../../redux/hooks';
import { useRouter } from 'next/router';
import {errorValue} from '@/redux/reducer/register';
const Content = styled.div`
    display:flex;
    background: linear-gradient(to top right,rgba(0,0,0, 0),rgba(28,44,91, 100)) center right/cover;
    height: 100vh;
    justify-content:center;
    align-items:center;
    width:100%;
`;

const InputWrapper = styled.input(
    ({ theme: {color} }) => css`
  background-color: ${color.badgeBackground};
  border-radius: 4px;
  font-size: 1rem;
  margin: 0.25rem;
  min-width: 305px;
  height: 3rem;
  padding: 0.5rem;
  border-style: none;
  &:focus {
    outline: none;
    box-shadow: 0px 0px 2px #1d686e;
`
)

export const LinkText = styled.a`
 text-decoration: none;
`;

function SignUp() {
  const dispatch = useAppDispatch();
  const router = useRouter();  
  const error = useAppSelector(errorValue);
 
     const formik = useFormik({
        initialValues: {
          email: '',
          password:''
        },
        validationSchema: Yup.object({
            email: Yup.string()
                      .email('Invalid email address')
                      .required('Email is required'),
            password: Yup.string()
                         .required('Password is required')
        }),
        onSubmit: values => {
        dispatch(signupuser(values));
        
        },
      });
  return (
    <>
    <Head>
      <title>Sign Up </title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <PageTemplate>
        <Content>
            <SignUpWrapper>
                <HeaderSign> Sign Up</HeaderSign>
                <FormWrapper onSubmit={formik.handleSubmit}>
                <InputWrapper type="email" name="email"placeholder="Enter Email Address" value={formik.values.email} onChange={formik.handleChange}required/>
                    <InputWrapper type="password" name="password"placeholder="Enter Password" value={formik.values.password} onChange={formik.handleChange}required/>
                    {error&& <div style={{color:"#AA1803", fontWeight: "bold"}}>{error.response.data}</div>}
                    <Button>Sign Up</Button>
                    <LinkText href="/signin">Login Instead&rarr;</LinkText>
                </FormWrapper>
            </SignUpWrapper>
        </Content>
    </PageTemplate>
    
    
    </>
  )
}

export default SignUp