import { PageTemplate } from '@/templates/PageTemplate';
import * as Yup from 'yup';
import {useFormik} from 'formik';
import Head from 'next/head'
import styled, {css} from 'styled-components'
import { HeaderSign, SignInWrapper, FormWrapper } from './index.style'
import React from 'react'
import Input from '@/components/Input/Input';


const Content = styled.div`
    display:flex;
    background: linear-gradient(to top right,rgba(0,0,0, 0),rgba(28,44,91, 100)) center right/cover;
    height: 100vh;
    justify-content:center;
    align-items:center;
    width:100%;
`;


function Signin() {

    const formik = useFormik({
        initialValues: {
          email: '',
          password:''
        },
        validationSchema: Yup.object({
            email: Yup.string()
                      .email('Invalid email address')
                      .required('Email is required'),
            password: Yup.string()
                         .required('Password is required')
        }),
        onSubmit: values => {
         console.log(values)
        },
      });

  return (
    <>
    <Head>
      <title>Sign In </title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <PageTemplate>
        <Content>
         <SignInWrapper>
            <HeaderSign>Sign In</HeaderSign>
            <FormWrapper onSubmit={formik.handleSubmit}>
            <Input name="email" placeholder='Enter your email' value={formik.values.email} onChange={formik.handleChange}/>
            <Input name="password" placeholder='Enter your password' value={formik.values.password} onChange={formik.handleChange}/>
            </FormWrapper>
         </SignInWrapper>
          
        </Content>
        
        
    </PageTemplate>

    </>
  )
}

export default Signin 