import { PageTemplate } from '@/templates/PageTemplate';
import * as Yup from 'yup';
import {useFormik} from 'formik';
import Head from 'next/head'
import styled, {css} from 'styled-components'
import { HeaderSign, SignInWrapper, FormWrapper } from './index.style'
import React, { useState} from 'react'
import Button from '@/components/Button/Button';
import { signinuser } from '@/redux/reducer/register';
import { errorValue, selectValue,loadingValue} from '@/redux/reducer/register';
import {paramsValue} from  '@/redux/reducer/location'
import {geoValue, getRealEstateData} from '@/redux/reducer/location'
import { useAppDispatch, useAppSelector } from '@/redux/hooks';
import { useRouter } from 'next/router';
import { Spinner } from '@/components/Spinner/Spinner';



const Content = styled.div`
    display:flex;
    background: linear-gradient(to top right,rgba(0,0,0, 0),rgba(28,44,91, 100)) center right/cover;
    height: 100vh;
    justify-content:center;
    align-items:center;
    width:100%;
`;

const InputWrapper = styled.input(
    ({ theme: {color} }) => css`
  background-color: ${color.badgeBackground};
  border-radius: 4px;
  font-size: 1rem;
  margin: 0.25rem;
  min-width: 305px;
  height: 3rem;
  padding: 0.5rem;
  border-style: none;
  &:focus {
    outline: none;
    box-shadow: 0px 0px 2px #1d686e;
`
)

export const LinkText = styled.a`
 text-decoration: none;
`;

function Signin() {
  const data = useAppSelector(selectValue);
  const params = useAppSelector(paramsValue);
  const geo = useAppSelector(geoValue);
  const error = useAppSelector(errorValue);
  const loading = useAppSelector(loadingValue)
  const dispatch = useAppDispatch()
  const router = useRouter();  
  console.log(data);
  data? router.push('/map'): null

  const formik = useFormik({
        initialValues: {
          email: '',
          password:''
        },
        validationSchema: Yup.object({
            email: Yup.string()
                      .email('Invalid email address')
                      .required('Email is required'),
            password: Yup.string()
                         .required('Password is required')
        }),
        onSubmit: async values => {
         dispatch(signinuser(values));
         await dispatch(getRealEstateData({type: 'sale', data: {...params, geo}}))
         
        },
      
      });

      
      
  return (
    <>
    <Head>
      <title>Sign In </title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <PageTemplate>
      
        <Content>
         <SignInWrapper>
          
            <HeaderSign>Sign In</HeaderSign>
            <FormWrapper onSubmit={formik.handleSubmit}>
           
            <InputWrapper type="email" name="email"placeholder="Enter Email Address" value={formik.values.email} onChange={formik.handleChange}required/>
            <InputWrapper type="password" name="password"placeholder="Enter Password" value={formik.values.password} onChange={formik.handleChange}required/>
            {error&& <div style={{color:"#AA1803", fontWeight: "bold"}}>{error.response.data}</div>}
          {  <Button disabled={loading==='loading'}>Sign In   { loading==='loading'? <Spinner/> : null }</Button>}
            
            <LinkText href="/signup">Register Instead&rarr;</LinkText>
            </FormWrapper>
            
         </SignInWrapper>
          
        </Content>
        
    </PageTemplate>
  
    </>
  )
}

export default Signin 

