import Head from 'next/head'
import Image from 'next/image'
import styled, {css} from 'styled-components'
import { Inter } from '@next/font/google'
import {PageTemplate} from '@/templates/PageTemplate';
import img from '../assets/images/homepage.jpg';
import Button from '@/components/Button/Button';
import HomepageBadge from '@/components/HomepageBadge/HomepageBadge';
import HomepageSection from '@/components/HomepageSection/HomepageSection';


const Content = styled.div`
background: url(${img.src}) center/cover;
display: flex;
justify-content: center;
align-items: center;
height: 40vh;
`;

const AddressInput = styled.input`
  
  background-color: #fff;
  border-radius: 4px;
  font-size: 1rem;
  margin: 0.25rem;
  min-width: 305px;
  height: 3rem;
  padding: 0.5rem;
  border-style: none;
  &:focus {
    outline: none;
    box-shadow: 0px 0px 2px #1d686e;
}
  `

  const Spacing = styled.div`
  margin-bottom: 4.5rem;
`

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <PageTemplate>
          <Content>
            <AddressInput type="text" placeholder="Enter address, or zipcode" required/>
          </Content> 
          <Spacing/>
          <HomepageSection/>
          <Spacing/>
          <div style={{display: 'flex', justifyContent:'center'}}>
          <HomepageBadge title="fjog" description='odfj'/>
          <HomepageBadge title="fjog" description='odfj'/>
          </div>
         
        </PageTemplate>
      </main>
    </>
  )
}
