import Head from 'next/head'
import Image from 'next/image'
import styled, {css} from 'styled-components'
import { breakpoints } from '@/styles/breakpoints';
import {PageTemplate} from '@/templates/PageTemplate';
import img from '../assets/images/homepage.jpg';
import Button from '@/components/Button/Button';
import HomepageBadge from '@/components/HomepageBadge/HomepageBadge';
import HomepageSection from '@/components/HomepageSection/HomepageSection';
import buylogo from '../assets/images/buy.png';
import rental from '../assets/images/rental.png';
import GooglePlacesAutocomplete, { geocodeByAddress } from 'react-google-places-autocomplete';
import { useAppDispatch } from '@/redux/hooks';
import { addlocation } from '@/redux/reducer/location';
import { useRouter } from 'next/router';


const Content = styled.div`
background: url(${img.src}) center/cover;
display: flex;
justify-content: center;
align-items: center;
height: 40vh;
`;

const AddressInput = styled.input`
  
  background-color: #fff;
  border-radius: 4px;
  font-size: 1rem;
  margin: 0.25rem;
  min-width: 305px;
  height: 3rem;
  padding: 0.5rem;
  border-style: none;
  &:focus {
    outline: none;
    box-shadow: 0px 0px 2px #1d686e;
}
  `

  const Spacing = styled.div`
  margin-bottom: 4.5rem;
`
const HomepageBadgecontainer = styled.div`
 display:flex;
 flex-direction: column;
 align-items: center;
 justify-content: space-evenly;
 @media ${breakpoints.M}{
  flex-direction: row;
  justify-content: center;
}
`

export default function Home() {
  const dispatch = useAppDispatch();
  const router = useRouter(); 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <PageTemplate>
          <Content>
              {/* <AddressInput type="text" placeholder="Enter address, or zipcode" required/>   */}
             <GooglePlacesAutocomplete
                apiKey={process.env.NEXT_PUBLIC_GOOGLE_API_KEY!}
                selectProps={{
                  placeholder: "Enter address, or zipcode..",
                  onChange: async ({ value }:any) => {
                    
                    const data = await geocodeByAddress(value.description);
                    console.log(data);
                    let dataDrive = { lat: data[0].geometry.location.lat(), lng: data[0].geometry.location.lng()} 
                    dispatch(addlocation(dataDrive))
                    router.push('/map')
                  },
                  styles: {
                    input: (provided: any) => ({
                      ...provided,
                      borderRadius: '4px',
                      minWidth:'350px',
                      outline:'none',
                      
                    }),
                  },
                }}
              />
          </Content> 
          <Spacing/>
          <HomepageSection/>
          <Spacing/>
          <HomepageBadgecontainer>
            <HomepageBadge logo={`${buylogo.src}`} title="Buy Home" description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam ' buttondesc= "Find a Home"/>
            <HomepageBadge logo={`${rental.src}`} title="Rent Home" description='Ac turpis egestas integer eget. Est lorem ipsum dolor sit. Convallis aenean et tortor at risus viverra. Ut tellus elementum sagittis vitae. Diam maecenas ultricies mi eget mauris.'buttondesc= "Find a Rental"/>
          </HomepageBadgecontainer>
          <Spacing/>
        </PageTemplate>
      </main>
    </>
  )
}
